#!/bin/zsh

BLACK=$'\033[30m'
RED=$'\033[31m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
BLUE=$'\033[34m'
MAGENTA=$'\033[35m'
CYAN=$'\033[36m'
WHITE=$'\033[37m'

BRIGHT_BLACK=$'\033[90m'
BRIGHT_RED=$'\033[91m'
BRIGHT_GREEN=$'\033[92m'
BRIGHT_BLUE=$'\033[94m'
BRIGHT_MAGENTA=$'\033[95m'
BRIGHT_CYAN=$'\033[96m'
BRIGHT_WHITE=$'\033[97m'

BOLD=$'\033[1m'
UNDERLINE=$'\033[4m'
ITALIC=$'\033[3m'

GRAY=$'\033[90m'

RESET=$'\033[0m'

AkiyamaMizukiIsTuff() {
  printf '%s\n' "$UNDERLINE${transBLUE}Aki${transPINK}yama${transWHITE} Mizu${transPINK}ki${RESET} is${transBLUE} $UNDERLINE${BOLD}tuff$RESET"
}

err(){
  printf '%s\n' "$RED$*$RESET"
}

log(){
  printf '%s\n' "$CYAN$*$RESET"
}

success() {
    printf '%s%s%s\n' "$GREEN" "$*" "$RESET"
}

warn() {
    printf '%s%s%s\n' "$YELLOW" "$*" "$RESET"
}

echo(){
  printf '%s\n' "$*"
}

HelpEcho(){
  printf '%-20s : %s\n' "$1" "$2"
}

ChkStatus() {
    local Unit="$1"

    local output
    output=$(launchctl print "$Domain$Unit" 2>&1)

    if (( $? != 0 )); then
        err "✗ $Unit"
        printf '  %s\n' "$output"
        return 1
    fi

    local state
    state=$(printf '%s\n' "$output" | awk -F' = ' '/^[[:space:]]*state = / {print $2; exit}')

    case "$state" in
        running)
            printf '%s●%s %s%s%s\n' \
                "$BRIGHT_GREEN" "$RESET" "$BOLD" "$Unit" "$RESET"
            printf '  State: %s%s%s\n' "$GREEN" "$state" "$RESET"
            ;;
        *)
            printf '%s●%s %s%s%s\n' \
                "$BRIGHT_YELLOW" "$RESET" "$BOLD" "$Unit" "$RESET"
            printf '  State: %s%s%s\n' "$YELLOW" "$state" "$RESET"
            ;;
    esac
}

StartSvc() {
  log "Starting $1"
  launchctl start "$Domain$1"
  if [[ $? != 0 ]]; then
    err "Failed to start $1."
    exit 1
  else
    success "Started $1."
  fi
}

StopSvc() {
  log "Stopping $1"
  launchctl stop "$Domain$1"
  if [[ $? != 0 ]]; then
    err "Failed to stop $1."
    exit 1
  else
    success "Stopped $1."
  fi
}

EnaSvc() {
  log "Enabling $1"
  launchctl enable "$Domain$1"
  if [[ $? != 0 ]]; then
    err "Failed to enable $1."
    exit 1
  else
    success "Enabled $1."
  fi
}

DisSvc() {
  log "Disabling $1"
  launchctl disable "$Domain$1"
  if [[ $? != 0 ]]; then
    err "Failed to disable $1."
    exit 1
  else
    success "Disabled $1."
  fi
}

LoadSvc(){
  if [[ -f "/System/Library/LaunchDaemons/${1}.plist" ]]; then
    Daemon="/System/Library/LaunchDaemons/${1}.plist"
  elif [[ -f "/rootfs/System/Library/LaunchDaemons/${1}.plist" ]]; then
    Daemon="/rootfs/System/Library/LaunchDaemons/${1}.plist"
  else
    err "Daemon not found!"
    exit 1
  fi
  log "Found daemon at $Daemon"
  log "Loading $1..."
  launchctl load "$Daemon"
  if [[ $? != 0 ]]; then
    err "Failed to load $1. May be the daemon is loaded."
    exit 1
  else
    success "Loaded $1."
  fi
}

UnLoadSvc(){
  if [[ -f "/System/Library/LaunchDaemons/${1}.plist" ]]; then
    uDaemon="/System/Library/LaunchDaemons/${1}.plist"
  elif [[ -f "/rootfs/System/Library/LaunchDaemons/${1}.plist" ]]; then
    uDaemon="/rootfs/System/Library/LaunchDaemons/${1}.plist"
  else
    err "Daemon not found!"
    exit 1
  fi
  log "Found daemon at $uDaemon"
  log "Unloading $1..."
  launchctl unload "$uDaemon"
  if [[ $? != 0 ]]; then
    err "Failed to unload $1. May be the daemon is not loaded."
    exit 1
  else
    success "Unloaded $1."
  fi
}

ShowHelp() {
  printf '%ssystemctl for iOS%s [command] ...\n' "$BOLD" "$RESET"
  printf '%s\n' "$ITALIC${GRAY}basically a launchctl wrapper.$RESET"
  printf '\n'
  printf '%sService%s commands :\n' "$UNDERLINE" "$RESET"
  HelpEcho "status  [service]" "Show status of [service]."
  HelpEcho "stop    [service]" "Stop [service]."
  HelpEcho "start   [service]" "Start [service]."
  HelpEcho "enable  [service]" "Enable [service]"
  HelpEcho "disable [service]" "Disable [service]"
  HelpEcho "restart [service]" "Restart [service]."
  HelpEcho "load    [service]" "Load [service]."
  HelpEcho "unload  [service]" "Unload [service]."
  HelpEcho "whoami" "Show your domain."

  printf '\n'  
  printf '%sSystem%s commands :\n' "$UNDERLINE" "$RESET"
  HelpEcho "soft-reboot" "Reboot userspace."
  HelpEcho "reboot" "Reboot the ${BOLD}system${RESET}. ${RED}Your jailbreak may be lost.${RESET} You have been warned."

}



if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
  ShowHelp
  exit 0
fi

if [[ $OSTYPE == linux* ]]; then
  if [[ $1 == '-l' ]] || [[ $1 == '--linux' ]]; then
    if [[ $(awk 'NR==1 {print $2; exit}' /proc/1/status) == "systemd" ]]; then
      warn "Redirecting to systemctl.."
      exec systemctl "$@[2,-1]"
    else
      err "--linux was requested, but PID 1 is not systemd."
      exit 1
    fi
  else
  err "Bro this is Linux. Use native systemctl or what the hell your distro give you."
    exit 1
  fi
fi



if [[ $(id -G) != 0 ]]; then
  err "no root :("
  exit 1
fi

Domain="user/$(id mobile -u)/"

case "$1" in
  status)
    ChkStatus "$2"
    ;;
  "")
    ShowHelp
    exit
    ;;
  start)
    StartSvc "$2"
    ;;
  whoami)
    echo "$Domain"
    ;;
  stop)
    StopSvc "$2"
    ;;
  enable)
    EnaSvc "$2"
    ;;
  disable)
    DisSvc "$2"
    ;;
  reboot)
    warn "WARNING: A full reboot may cause your jailbreak to be lost."
    warn "Consider using 'systemctl soft-reboot' instead."
    printf "Continue with full reboot? [y/N]: "

    read -r answer

    if [[ "$answer" != [yY] ]]; then
        info "Reboot cancelled."
        exit 0
    fi

    launchctl reboot system
    ;;
  soft-reboot)
    launchctl reboot userspace
    ;;
  help)
    ShowHelp
    ;;
  restart)
    StopSvc "$2" || exit $?
    StartSvc "$2"
    ;;
  load)
    LoadSvc "$2"
    ;;
  unload)
    UnLoadSvc "$2"
    ;;
  *)
    err "Idk what command is $UNDERLINE$BOLD$1$RESET${RED}."
    ShowHelp
    exit 1
    ;;
esac

AkiyamaMizukiIsTuff
